name: Print Hello Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: your-username/printhello  # Replace 'your-username' with your GitHub username

    - name: Print Hello
      run: echo "Hello, World!"
